theme = "hugo-paper"
defaultContentLanguage = "pt"
enableEmoji = true

disqusShortname = 'professor-enoqueleal-github-io'

[pagination]
  pagerSize = 3

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'enoquefsleal'                  # twitter.com/enoquefsleal
  github = 'professor-enoqueleal'           # github.com/professor-enoqueleal
  instagram = 'enoque.dev'                  # instagram.com/enoque.dev
  youtube = '@enoque-dev'                   # youtube.com/@enoque-dev

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/127161266?v=4'

[languages]
  [languages.pt]
    languageCode = "pt"
    languageName = "Português"
    title = "Car Store"
    weight = 1
    [languages.pt.params]
      name = 'Enoque Leal'
      bio = 'Ninguém é tão grande que não possa aprender, nem tão pequeno que não possa ensinar.'

    [[languages.pt.menu.main]]
      identifier = "about"
      name = "Sobre"
      url = "/about/"
      weight = 10
    [[languages.pt.menu.main]]
      identifier = "contact"
      name = "YouTube"
      url = "http://youtube.com/@enoque-dev"
      weight = 10

  [languages.en]
    languageCode = "en"
    languageName = "English"
    title = "Car Store"
    weight = 2
    [languages.en.params]
      name = 'Enoque Leal'
      bio = 'No one is so great that they cannot learn, nor so small that they cannot teach.'

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/en/about/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "contact"
      name = "YouTube"
      url = "http://youtube.com/@enoque-dev"
      weight = 10



