theme = "hugo-paper"
title = "Car Store"
languageCode = "pt"
DefaultContentLanguage = "pt"
enableEmoji = true

disqusShortname = 'professor-enoqueleal-github-io'

[pagination]
  pagerSize = 3

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'enoquefsleal'                  # twitter.com/enoquefsleal
  github = 'professor-enoqueleal'           # github.com/professor-enoqueleal
  instagram = 'enoque.dev'                  # instagram.com/enoque.dev
  youtube = '@enoque-dev'                   # youtube.com/@enoque-dev

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/127161266?v=4'
  name = 'Enoque Leal'
  bio = 'Ninguém é tão grande que não possa aprender, nem tão pequeno que não possa ensinar.'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "YouTube"
    url = "http://youtube.com/@enoque-dev"
    weight = 10




